server:
  port: 8080

spring:
  application:
    name: local-grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9898'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext